version: '3.8'

services:
  review-gpt:
    image: codehouseou/review-gpt:1.0.7
    environment:
      - GH_AUTH=${GH_AUTH}
      - ENDPOINT=${ENDPOINT}
      - API_KEY=${API_KEY}
      - MODEL_NAME=${MODEL_NAME}
      - API_VERSION=${API_VERSION}
      # Optional: define Github instance API url
#      - GH_API=${GH_API}
      # Optional: define the system prompt for the LLM model
#      - PROMPT=${PROMPT}
    ports:
      - "8080:5000"
